// Notification
export const SHOW_NOTIFICATION = 'SHOW_NOTIFICATION'
export const CLEAR_NOTIFICATION = 'CLEAR_NOTIFICATION'

// Lions
export const SET_SEARCH = 'SET_SEARCH'
export const SET_ALL_LIONS = 'SET_ALL_LIONS'
export const SET_MARKETPLACE = 'SET_MARKETPLACE'
export const SET_MY_LIONS = 'SET_MY_LIONS'
export const SET_POLL_INTERVAL_LIONS = 'SET_POLL_INTERVAL_LIONS'
export const CLEAR_POLL_INTERVAL_LIONS = 'CLEAR_POLL_INTERVAL_LIONS'

// Web3 JS
export const METAMASK = 'SET_METAMASK'
export const IS_LOADING = 'SET_ISLOADING'
export const SET_NETWORK = 'SET_NETWORK'
export const SET_ACCOUNT = 'SET_ACCOUNT'
export const IS_MY_LION = 'IS_MY_LION'
export const SET_ETH_BALANCE = 'SET_ETH_BALANCE'
export const SET_TOKEN_BALANCE = 'SET_TOKEN_BALANCE'
export const SET_DECIMALS = 'SET_DECIMALS'
export const SET_CONNECTED = 'SET_CONNECTED'
export const SET_POLL_INTERVAL = 'SET_POLL_INTERVAL'
export const CLEAR_POLL_INTERVAL = 'CLEAR_POLL_INTERVAL'
export const ETH_DISCONNECT = 'ETH_DISCONNECT'
